Update check_version.yml

diff --git a/.github/workflows/check_version.yml b/.github/workflows/check_version.yml
--- a/.github/workflows/check_version.yml
+++ b/.github/workflows/check_version.yml
@@ -19,13 +19,13 @@ jobs:
           "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
         
         # Check if versions are empty or null
-        #if [ -z "$WSDDN_V" ] || [ "$WSDDN_V" = "null" ] || [ -z "$AVAILABLE_V" ] || [ "$AVAILABLE_V" = "null" ]; then
-        #  echo "Couldn't get Version numbers"
-        #  exit 1
-        #fi
+        if [ -z "$WSDDN_V" ] || [ "$WSDDN_V" = "null" ] || [ -z "$AVAILABLE_V" ] || [ "$AVAILABLE_V" = "null" ]; then
+          echo "Couldn't get Version numbers"
+          exit 1
+        fi
 
-        if [ "${WSDDN_V#*-}" != "${AVAILABLE_V#v}" ]; then
-          echo "Newer version found: v${WSDDN_V#*-}"
+        if [ "${WSDDN_V}" != "${AVAILABLE_V}" ]; then
+          echo "Newer version found: ${WSDDN_V}"
           curl -X POST \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
